/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatusRouteImport } from './routes/status'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardNewScanIndexRouteImport } from './routes/dashboard/new-scan/index'
import { Route as DashboardScanIdRouteImport } from './routes/dashboard/scan/$id'

const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardNewScanIndexRoute = DashboardNewScanIndexRouteImport.update({
  id: '/dashboard/new-scan/',
  path: '/dashboard/new-scan/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardScanIdRoute = DashboardScanIdRouteImport.update({
  id: '/dashboard/scan/$id',
  path: '/dashboard/scan/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/network': typeof NetworkRoute
  '/privacy': typeof PrivacyRoute
  '/status': typeof StatusRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/scan/$id': typeof DashboardScanIdRoute
  '/dashboard/new-scan/': typeof DashboardNewScanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/network': typeof NetworkRoute
  '/privacy': typeof PrivacyRoute
  '/status': typeof StatusRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/scan/$id': typeof DashboardScanIdRoute
  '/dashboard/new-scan': typeof DashboardNewScanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/network': typeof NetworkRoute
  '/privacy': typeof PrivacyRoute
  '/status': typeof StatusRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/scan/$id': typeof DashboardScanIdRoute
  '/dashboard/new-scan/': typeof DashboardNewScanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/network'
    | '/privacy'
    | '/status'
    | '/dashboard/'
    | '/dashboard/scan/$id'
    | '/dashboard/new-scan/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/network'
    | '/privacy'
    | '/status'
    | '/dashboard'
    | '/dashboard/scan/$id'
    | '/dashboard/new-scan'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/network'
    | '/privacy'
    | '/status'
    | '/dashboard/'
    | '/dashboard/scan/$id'
    | '/dashboard/new-scan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  NetworkRoute: typeof NetworkRoute
  PrivacyRoute: typeof PrivacyRoute
  StatusRoute: typeof StatusRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardScanIdRoute: typeof DashboardScanIdRoute
  DashboardNewScanIndexRoute: typeof DashboardNewScanIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/new-scan/': {
      id: '/dashboard/new-scan/'
      path: '/dashboard/new-scan'
      fullPath: '/dashboard/new-scan/'
      preLoaderRoute: typeof DashboardNewScanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/scan/$id': {
      id: '/dashboard/scan/$id'
      path: '/dashboard/scan/$id'
      fullPath: '/dashboard/scan/$id'
      preLoaderRoute: typeof DashboardScanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  NetworkRoute: NetworkRoute,
  PrivacyRoute: PrivacyRoute,
  StatusRoute: StatusRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardScanIdRoute: DashboardScanIdRoute,
  DashboardNewScanIndexRoute: DashboardNewScanIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
